<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="8" hostname="Nitya" name="com.qa.opencart.tests.ProductPageTest" tests="9" failures="0" timestamp="31 Mar 2023 08:58:33 GMT" time="0.050" errors="1">
  <testcase name="productHeaderTest" time="0.000" classname="com.qa.opencart.tests.ProductPageTest">
    <skipped/>
  </testcase> <!-- productHeaderTest -->
  <testcase name="productHeaderTest" time="0.000" classname="com.qa.opencart.tests.ProductPageTest">
    <skipped/>
  </testcase> <!-- productHeaderTest -->
  <testcase name="setup" time="0.049" classname="com.qa.opencart.tests.ProductPageTest">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.qa.opencart.factory.DriverFactory.initDriver(DriverFactory.java:68)
	at com.qa.opencart.base.BaseTest.setup(BaseTest.java:31)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:523)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:224)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:146)
	at org.testng.TestRunner.beforeRun(TestRunner.java:626)
	at org.testng.TestRunner.run(TestRunner.java:594)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:414)
	at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- setup -->
  <testcase name="productHeaderTest" time="0.001" classname="com.qa.opencart.tests.ProductPageTest">
    <skipped/>
  </testcase> <!-- productHeaderTest -->
  <testcase name="getProductImageCountTest" time="0.000" classname="com.qa.opencart.tests.ProductPageTest">
    <skipped/>
  </testcase> <!-- getProductImageCountTest -->
  <testcase name="getProductImageCountTest" time="0.000" classname="com.qa.opencart.tests.ProductPageTest">
    <skipped/>
  </testcase> <!-- getProductImageCountTest -->
  <testcase name="getProductImageCountTest" time="0.000" classname="com.qa.opencart.tests.ProductPageTest">
    <skipped/>
  </testcase> <!-- getProductImageCountTest -->
  <testcase name="productMetaDataTest" time="0.000" classname="com.qa.opencart.tests.ProductPageTest">
    <skipped/>
  </testcase> <!-- productMetaDataTest -->
  <testcase name="productPriceMetaDataTest" time="0.000" classname="com.qa.opencart.tests.ProductPageTest">
    <skipped/>
  </testcase> <!-- productPriceMetaDataTest -->
</testsuite> <!-- com.qa.opencart.tests.ProductPageTest -->
